### ISSUE TITLE
Support for brew tap: add formula to the homebrew-xctesthtmlreport repository

### ISSUE THREAD

**Issue by albertodebortoli** [XCTestHTMLReport/XCTestHTMLReport#182]
According to https://docs.brew.sh/Taps, could you please add the formula (https://github.com/TitouanVanBelle/XCTestHTMLReport/blob/develop/xchtmlreport.rb) to your already existing repo https://github.com/TitouanVanBelle/homebrew-xctesthtmlreport?

Brew 2.5.0 started failing with 
```
Error: Calling Non-checksummed download of xchtmlreport formula file from an arbitrary URL is disabled!
```

Would also be nice to update the installation instructions in the README:

```
brew install TitouanVanBelle/XCTestHTMLReport/xchtmlreport
```

**Comment by ChiWhiteSox56** [comment]
I encountered this too. As a workaround, I'm installing with curl until the Brew issue is fixed.

**Comment by triztian** [comment]
I'm running into the same issue:

```
➜  date && brew install --HEAD https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb
Mon Sep 14 17:26:50 PDT 2020
Updating Homebrew...
Error: Calling Non-checksummed download of xchtmlreport formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
```

**Comment by nacho4d** [comment]
Sorry this comes after a long time... 

I followed the steps mentioned by @albertodebortoli and now the [Brew tap repository](https://github.com/XCTestHTMLReport/homebrew-xchtmlreport) works!. 

Thank you @albertodebortoli 

README has been updated to reflect the change.  BTW, if you use [Mint](https://github.com/yonaskolb/Mint) it is even easier...

I am closing this issue since I think it is already fixed. If you have problems reopen please :) 

> ### Mint
>
> Mint is the easiest way...
> 
> Install latest stable version
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport
>
> Install latest from develop branch
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport@develop
>
> ### Homebrew
> 
> Install latest stable version
> 
>     brew install XCTestHtmlReport/xchtmlreport/xchtmlreport
>
> Install latest from develop branch
> 
>     $ wget https://raw.githubusercontent.com/XCTestHTMLReport/XCTestHTMLReport/develop/xchtmlreport.rb
>     $ brew install --HEAD --build-from-source xchtmlreport.rb
