### ISSUE TITLE
Special characters in scheme/test output names causing problems

### ISSUE THREAD

**Issue by ratkins** [XCTestHTMLReport/XCTestHTMLReport#184]
The `.xcresult` directory is, by default, named for the scheme executed. Our scheme names used to have parenthesis characters in them, but they appeared to be being interpreted by something inside XCTestHTMLReport as delineating regex capture groups and causing an error. I changed the scheme names from `Foo (Bar)` to `Foo - Bar`, and now the `-` character seems to be causing an issue.

I believe I'm quoting everything properly in my shell invocation, is there any way around this without making sure the scheme names don't have "special" (not really that special) characters in them?

**Comment by ratkins** [comment]
(This may indeed be fixed by #165 but that was merged after 2.0.0 was cut and the install instructions don't detail a way of installing from the current master.)

**Comment by nacho4d** [comment]
I would like to look into this.

**Comment by ratkins** [comment]
Please, and I’m happy to test it again. I think the most important thing is to cut another release, as right now there’s no way for me to install the HEAD version into the VM in our CI pipeline to see if the existing fixes for spaces in path names help us.

**Comment by nacho4d** [comment]
@ratkins It is being a long time. ?
I think names are already ok in latest release.  Can you try with the latest version? (2.2.1)

**Comment by ratkins** [comment]
Blast from the past :). I’m afraid I’ve long since moved on from the project where this was causing a problem, so I have no way to test if it’s fixed.

**Comment by nacho4d** [comment]
Got it!. Thank you.
Since I think this is indeed solved I am going to close this issue.
If someone has the same problem it is possible to reopen this again :)
