### ISSUE TITLE
Homebrew HEAD installation fails "Calling Non-checksummed download"

### ISSUE THREAD

**Issue by chrisballinger** [XCTestHTMLReport/XCTestHTMLReport#190]
```
#!/bin/bash --login -eo pipefail
brew install --HEAD https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb

Error: Calling Non-checksummed download of xchtmlreport formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.

Exited with code exit status 1
```

For more information: https://github.com/TitouanVanBelle/XCTestHTMLReport/issues/182#issuecomment-709771775

Workaround:

```
$ curl -O https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb
$ brew install --HEAD --build-from-source xchtmlreport.rb
```

Longer term it would be good to set up a tap as referenced in #182

**Comment by kenji21** [comment]
I also noticed that version is still 2.0.0 after running workaround commands

**Comment by chrisballinger** [comment]
@kenji21 The version printed out on the console is still `2.0.0` until #189 is merged

**Comment by nacho4d** [comment]
@chrisballinger Thank you for pointing me into the right direction. 

[Brew tap repository](https://github.com/XCTestHTMLReport/homebrew-xchtmlreport) is new it works now!. README has been updated to reflect the change. Also, if you use [Mint](https://github.com/yonaskolb/Mint) it is even easier...

I am closing this issue since I think it is already fixed. If you have problems reopen please :) 

> ### Mint
>
> Mint is the easiest way...
> 
> Install latest stable version
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport
>
> Install latest from develop branch
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport@develop
>
> ### Homebrew
> 
> Install latest stable version
> 
>     brew install XCTestHtmlReport/xchtmlreport/xchtmlreport
>
> Install latest from develop branch
> 
>     $ wget https://raw.githubusercontent.com/XCTestHTMLReport/XCTestHTMLReport/develop/xchtmlreport.rb
>     $ brew install --HEAD --build-from-source xchtmlreport.rb
