### ISSUE TITLE
Not inline screenshot when using image compression -z

### ISSUE THREAD

**Issue by feliciaamanda** [XCTestHTMLReport/XCTestHTMLReport#202]
Hi guys, I just wonder to use image compression (-z) to reduce my report file size, but after implement this, screenshot not shown in CI report attachment. But I can't also use 2 BlockArguments in same time (-i and -z). Can I still reduce image size and inline it too? Thankyou.

**Comment by nacho4d** [comment]
Would be nice to allow those two arguments ... I will add the "Feature" label.

**Comment by thisisjeffwong** [comment]
Could the images be resized before the HTML is built? Seems like resizing before inlining would make the resulting file smaller.

**Comment by tylervick** [comment]
This should be fixed by #253 `-z` and `-i` may be run simultaneously. This also implicitly converts the heic encoding to jpeg, since Chrome does not natively support heic/heif..
