### ISSUE TITLE
How about making XCTestHTMLReport an organization?

### ISSUE THREAD

**Issue by nacho4d** [XCTestHTMLReport/XCTestHTMLReport#210]
Hi,

I use this incredible useful tool and I really like it! Yeah it has some bugs and things that can improved so I try to submit pull requests whenever I can... However I have noticed that this repository is becoming a bit unmaintained and pull requests take various weeks or even months to get merged. 

@TitouanVanBelle Have you considered making this repository an Organization? I would really like this tool to be always here working with the latest Xcode so making this an organization will allow more people from the community to contribute and be able to merge sooner.

I do not represent my company/employer in any way. I just thought there are several areas we can work and making this repo an organization we could speed up the merging process by delegating to various other members.

@TitouanVanBelle I hope you think about it. Thanks for this great tool anyways!

**Comment by TitouanVanBelle** [comment]
Hi @nacho4d,

I'm all for giving this repository to the community. What do you mean exactly with making this repository an organization? Should I create an organization and move this repository's ownership to the organisation? 

If you feel like it you can start doing this and I'll transfer the ownership to the newly created organisation.

What do you think?

**Comment by nacho4d** [comment]
@TitouanVanBelle 

Thank you for all the support!

Yes.

I have created this organization: https://github.com/XCTestHTMLReport 
If you are OK you can move this repository to the new organization. 

I have invited you as owner and If you are ok we can invite more and more members and collaborators.

I have tested with a toy repo and another toy organization and GitHub will redirect all pull/push commands to the organization even if the user has the old git address as its remote. This is quite nice.

**Comment by tylervick** [comment]
Echoing huge support for this change - I was already in progress creating a fork with CD since we often see breakages with new versions of Xcode. I'm happy to make a PR for this new org - we'll just need an admin to provide a couple secrets for code signing.

**Comment by TitouanVanBelle** [comment]
Hey @nacho4d,

Thanks for taking care of this. Could you resend the invitation to the
organization. It expired after 7 days and is not valid anymore. I'll take a
look at it this today or later this week.

Cheers

Le lun. 20 sept. 2021 à 00:30, Tyler Vick ***@***.***> a
écrit :

**Comment by nacho4d** [comment]
@TitouanVanBelle I just send it now. I hope you can see it this time :)

**Comment by TitouanVanBelle** [comment]
Yes thank you. Ownership has been transferred

**Comment by nacho4d** [comment]
@TitouanVanBelle Wow! It has been done! Thank you for all the effort @TitouanVanBelle !
I will close this issue now :)
