### ISSUE TITLE
installation error when installing via brew: Invalid usage: Non-checksummed download of xchtmlreport

### ISSUE THREAD

**Issue by arielelkin** [XCTestHTMLReport/XCTestHTMLReport#211]
Installation fails when following [the brew installation instructions](https://github.com/TitouanVanBelle/XCTestHTMLReport#homebrew).

```
$ brew install https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and caskroom/cask).
==> New Formulae
actionlint                        clickhouse-cpp                    libavif                           lziprecover                       red-tldr
bottom                            gtop                              lunzip                            pkg-config-wrapper                viddy
==> Updated Formulae
Updated 342 formulae.
==> Deleted Formulae
vavrdiasm
==> New Casks
notunes                      notunes                      remix-ide                    remix-ide                    universal-gcode-platform     universal-gcode-platform
==> Updated Casks
Updated 262 casks.

Traceback (most recent call last):
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of xchtmlreport formula file from an arbitrary URL is unsupported!  (UsageError)
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of xchtmlreport formula file from an arbitrary URL is unsupported!  (UsageError)
```

Using Homebrew 3.2.13
macOS 11.4

**Comment by nacho4d** [comment]
@arielelkin 
[Brew tap repository](https://github.com/XCTestHTMLReport/homebrew-xchtmlreport) is new now it works!. README has been updated to reflect the change. Also, if you use [Mint](https://github.com/yonaskolb/Mint) it is even easier...

I am closing this issue since I think it is already fixed. If you have problems reopen please :) 

> ### Mint
>
> Mint is the easiest way...
> 
> Install latest stable version
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport
>
> Install latest from develop branch
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport@develop
>
> ### Homebrew
> 
> Install latest stable version
> 
>     brew install XCTestHtmlReport/xchtmlreport/xchtmlreport
>
> Install latest from develop branch
> 
>     $ wget https://raw.githubusercontent.com/XCTestHTMLReport/XCTestHTMLReport/develop/xchtmlreport.rb
>     $ brew install --HEAD --build-from-source xchtmlreport.rb
