### ISSUE TITLE
Inlining causes memory leak and/or infinite loop

### ISSUE THREAD

**Issue by thisisjeffwong** [XCTestHTMLReport/XCTestHTMLReport#238]
I've noticed that some result files from Xcode 12.5 and Xcode 13 cause the process to consume about 75GB of virtual memory when trying to do inlining of images, until killed by the OS for running out of memory. Without inlining, it completes in about 20 minutes. The test results file itself is only 450MB large.

Is there an obvious way this could be prevented?

**Comment by nacho4d** [comment]
Recently a memory problem was addressed in this pull request https://github.com/XCTestHTMLReport/XCTestHTMLReport/pull/230 . It is not release yet. I mention it since it could be one of the reasons of this issue.

**Comment by thisisjeffwong** [comment]
Thanks, I was able to finish my runs with the top of main branch.
