### ISSUE TITLE
The generated .junit XML report file validation is failing

### ISSUE THREAD

**Issue by tarakeswa** [XCTestHTMLReport/XCTestHTMLReport#248]
Hi Team,

Used following command `xchtmlreport -r TestResults -j`

I see that report.junit file is created after my test execution is finished on my iOS device. But when I copy the content from the report.junit file and trying to validate its format using XML validation sites, it shows syntax errors. 

Looks like the report is not formatted correctly according to the XML syntax. Can anyone please look into this issue?

I have attached the file in .txt file by copied the generated Junit XML content as it is not accepting the .junit file for your reference
<img width="1536" alt="Screenshot 2022-01-05 at 6 21 13 PM" src="https://user-images.githubusercontent.com/47081202/148220669-1ba26913-c1b3-4d9f-b08b-05751c3453c4.png">
[Got this content from report.junit file.txt](https://github.com/XCTestHTMLReport/XCTestHTMLReport/files/7814987/Got.this.content.from.report.junit.file.txt)

**Comment by nacho4d** [comment]
Thank you for reporting this. I will look in to this. 

I think the name of your device is the origin of the error since it has a `'` in it: `Tarakeswara's iPhone 7`.  So if you are in a hurry you can rename your iPhone to something else.

**Comment by nacho4d** [comment]
It checked the source and it looks it should be solved already (about one year ago). Are you using the latest version?

- It was fixed in the [pull request](https://github.com/XCTestHTMLReport/XCTestHTMLReport/pull/196/files).
- If needed, you can refer to the updated [README.md](https://github.com/XCTestHTMLReport/XCTestHTMLReport/blob/main/README.md) for installation instructions.

**Comment by tarakeswa** [comment]
I am using the 2.0.0 version. Thanks for pointing the problem, I will update to the latest software. thank you so much for looking into it.

**Comment by nacho4d** [comment]
I should clarify. It was fixed like a year ago but it was released on [October 2021 Latest Version 2.2.0](https://github.com/XCTestHTMLReport/XCTestHTMLReport/releases/tag/2.2.0).
> Escaping of class names, test names, suite names
