### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by TangGuowei** [XCTestHTMLReport/XCTestHTMLReport#256]
brew install XCTestHtmlReport/xchtmlreport/xchtmlreport

Error: SHA256 mismatch
Expected: c1e454dedae3373414d0bafd8dac0a8b0afb6daddd475108b5e577ae8d7496c1
  Actual: 812bb0655517a705a06a931a0a9b59c674064018e8c946dee81817c7a1df327a
    File: /Users/bkdevops/Library/Caches/Homebrew/downloads/892a51eb2f6d6d239f2e15d2cad329c090c8f656b1300f7f6410ac284ec14afd--XCTestHTMLReport-2.2.1.tar.gz
To retry an incomplete download, remove the file above.

**Comment by yjchiu18** [comment]
⚠️same here.⚠️

**Comment by tylervick** [comment]
Sorry for that! A new CI job calculated SHAs incorrectly. I've manually corrected this and it should be live now - Will follow up with a fix for the GH action script.

**Comment by aistetests** [comment]
I am still getting it (via brew)

**Comment by teerayuthton** [comment]
Same issue

`brew install XCTestHtmlReport/xchtmlreport/xchtmlreport

==> Downloading from https://codeload.github.com/XCTestHTMLReport/XCTestHTMLReport/tar.gz/refs/tags/2.2.1
# #=O#- #                                                                     
Error: xchtmlreport: SHA256 mismatch
Expected: c1e454dedae3373414d0bafd8dac0a8b0afb6daddd475108b5e577ae8d7496c1
  Actual: 812bb0655517a705a06a931a0a9b59c674064018e8c946dee81817c7a1df327a
    File: /Users/ton/Library/Caches/Homebrew/downloads/892a51eb2f6d6d239f2e15d2cad329c090c8f656b1300f7f6410ac284ec14afd--XCTestHTMLReport-2.2.1.tar.gz
To retry an incomplete download, remove the file above.
`

**Comment by tylervick** [comment]
Sorry about this whole problem everyone - https://github.com/XCTestHTMLReport/homebrew-xchtmlreport/blob/84c552ae25b0fa9d3c162d928e1369e13c374c7c/xchtmlreport.rb#L5 reflects the actual sha now

**Comment by aistetests** [comment]
Got it working eventually after brew update and brew upgrade. Thanks!

**Comment by tylervick** [comment]
Thank you! Please reopen if you're still seeing this.
