### ISSUE TITLE
.plist file not found

### ISSUE THREAD

**Issue by bdmariobd** [XCTestHTMLReport/XCTestHTMLReport#259]
In my test, the .plist file is not called 'Info', is generated with other name. Is there a XCTestHTMLReport to specify this file name?

**Comment by nacho4d** [comment]
@bdmariobd Sorry for the late reply.

Could you specify what command are you running?

XCTestHTMLReport uses `*.xcresult` files which should created by yourself. I am not aware that XCTestHTMLReport directly uses Info.plist so if you provide an example I can try it.
