### ISSUE TITLE
Xcode 14 support

### ISSUE THREAD

**Issue by ntduyet** [XCTestHTMLReport/XCTestHTMLReport#273]
Hello, thanks for building this awesome tool. 

We're working on Xcode 14 support and notice there are some unexpected changes in `xcresult` format compared to Xcode 13.x. One breaking change is `ActivityTestSummary.activitySummaries` no longer include `com.apple.dt.xctest.activity-type.testAssertionFailure` type which causes the generated HTML/Junit report doesn't show up any failure reason/message and the corresponding attachments.

Not sure if it's a regression bug so we already filed a feedback to Apple. However, we should be prepared in case that change is intended. 

Please download [xcresults.zip](https://github.com/XCTestHTMLReport/XCTestHTMLReport/files/9309464/xcresults.zip) including`xcresult` files when running test with Xcode 13.4 and Xcode 14 beta 5 and try generating the HTML/Junit report to spot the issue.

**Comment by chri7325** [comment]
I've also just started hitting this issue as well with Xcode 14. The HTML report correctly shows the failed tests but the junit shows the tests as passing so we're not able to have Jenkins report on the results correctly.

**Comment by tylervick** [comment]
Adding some additional details -

It appears that the top-level summary still reflects the correct status count. But as others noted, the `<failure>` tag is not present in any report from an Xcode 14-based xcresult bundle.

It looks like xcresulttool 3.39 removed the `testAssertionFailure` type.

We still have `ActionTestFailureSummary`, though it's a separate section from the other test summary steps. One possibility is to combine these two sets and order by the recorded timestamp. It's not ideal but might be the best thing we can do at the moment.

**Comment by ssharma0312** [comment]
I am encountering exact same issue. I no longer see "<failure>" tag in the junit report produced on XCode 14 .xcresult file.

**Comment by tylervick** [comment]
Fix was released in #291 - please comment if you're still seeing issues!

**Comment by chri7325** [comment]
@tylervick I updated this tool with brew and now we're getting correct results. You guys rock!
