### ISSUE TITLE
No available formula with the name "titouanvanbelle/xctesthtmlreport/xchtmlreport"

### ISSUE THREAD

**Issue by TitouanVanBelle** [XCTestHTMLReport/XCTestHTMLReport#86]
@chrisballinger I can't seem to be able to install `xchtmlreport` through brew. Any idea what's happening there?

```
~[19:12:09]
$ brew install TitouanVanBelle/XCTestHTMLReport/xchtmlreport
==> Tapping titouanvanbelle/xctesthtmlreport
Cloning into '/usr/local/Homebrew/Library/Taps/titouanvanbelle/homebrew-xctesthtmlreport'...
warning: You appear to have cloned an empty repository.
Tapped 0 formulae (3 files, 1.9KB)
Error: No available formula with the name "titouanvanbelle/xctesthtmlreport/xchtmlreport"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.

~[19:12:25]
$ brew tap
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
homebrew/cask
homebrew/cask-versions
homebrew/core
titouanvanbelle/xctesthtmlreport

~[19:12:39]
$ brew untap titouanvanbelle/xctesthtmlreport
Untapping titouanvanbelle/xctesthtmlreport... (5 files, 2.9KB)
Untapped 0 formulae

~[19:12:44]
$ brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by krin-san** [comment]
Same for me. Can't install this tool using Homebrew

**Comment by kdbertel** [comment]
I am having this problem as well. Are there any plans for a fix? Better, are there any plans to include the formula in Homebrew directly?

**Comment by chrisballinger** [comment]
Homebrew won't merge the formula unless this repo has more than 50 stars

**Comment by krin-san** [comment]
50 stars? That's doable. Already integrated this tool on my project and the results is really satisfying! Gave my star to it.

**Comment by TitouanVanBelle** [comment]
We got them now :)

**Comment by TitouanVanBelle** [comment]
@chrisballinger Any update on this?

**Comment by kdbertel** [comment]
The pull request in question is here: https://github.com/Homebrew/homebrew-core/pull/26977

It was rejected because the notoriety requirements are:
- 20+ forks
- 20+ watchers
- 50+ stars

**Comment by kdbertel** [comment]
I don't suppose there's a way we could at least create a tap for this, until it meets the notoriety requirements? That would make it much easier to use with `Brewfile`.

**Comment by kdbertel** [comment]
I've been trying to spread the word around as best I can. I'll keep trying, though! :)

**Comment by krin-san** [comment]
Repo now meet the requirements with 20 watchers. Can we re-open PR?

**Comment by nacho4d** [comment]
As suggested by #182 I created a [Brew tap repository](https://github.com/XCTestHTMLReport/homebrew-xchtmlreport) and brew one-liner installation now works again!. README has been updated to reflect the change. 

BTW, if you use [Mint](https://github.com/yonaskolb/Mint) it is even easier...

I am closing this issue since I think it is already fixed. If you have problems reopen please :) 

> ### Mint
>
> Mint is the easiest way...
> 
> Install latest stable version
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport
>
> Install latest from develop branch
> 
>     mint install XCTestHTMLReport/XCTestHTMLReport@develop
>
> ### Homebrew
> 
> Install latest stable version
> 
>     brew install XCTestHtmlReport/xchtmlreport/xchtmlreport
>
> Install latest from develop branch
> 
>     $ wget https://raw.githubusercontent.com/XCTestHTMLReport/XCTestHTMLReport/develop/xchtmlreport.rb
>     $ brew install --HEAD --build-from-source xchtmlreport.rb
